version: '2'
volumes:
  data:
    driver_opts:
      export: /mnt/plex
      host: pi.cbphoto.ca
    driver: rancher-nfs
  transcode:
    driver_opts:
      exportBase: /mnt/plex/rancher/transcode
      host: pi.cbphoto.ca
    driver: rancher-nfs
  config:
    driver_opts:
      exportBase: /mnt/plex/rancher/config
      host: pi.cbphoto.ca
    driver: rancher-nfs
services:
  plex:
    image: plexinc/pms-docker
    environment:
      TZ: ' "PST"'
    volumes:
    - config:/config:nocopy
    - transcode:/transcode:nocopy
    - data:/data:nocopy
    ports:
    - 32400:32400/tcp
    - 3005:3005/tcp
    - 8324:8324/tcp
    - 32469:32469/tcp
    - 1900:1900/udp
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
    labels:
      io.rancher.container.pull_image: always